services:
  gatekeeper:
    image: gatekeeper:local # <-- Matches the tag built by your workflow step
    container_name: gatekeeper
    ports:
      - "80:80"
    environment:
      # Change this IP whenever you want to point traffic to a different target
      - TARGET_IP=192.168.0.200:80 
    restart: always
