server {
    listen 3000;
    server_name localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /uploads/ {
        proxy_pass http://192.168.0;
        
        # Inject your secret security key silently here
        proxy_set_header X-API-Key "BlockAllWithoutKey";
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

}

