server {
    listen 80;
    server_name 192.168.0.202; # Your Image Server VM IP

    # Allows large photo uploads from your Web API VM to this server
    client_max_body_size 100M; 

    # 1. ROUTE FOR FAST THUMBNAILS
    location /uploads/thumbs/ {
        alias /var/www/photo-app/uploads/thumbs/;
        expires 30d;
        add_header Cache-Control "public, no-transform";

        # Whitelists your local test setups and your dedicated React VM
        valid_referers none blocked localhost localhost:3000 192.168.0.200;
        if ($invalid_referer) {
            return 403;
        }
    }

    # 2. MAIN IMAGES
    location /uploads/ {
        alias /var/www/photo-app/uploads/;
        expires 30d;
        add_header Cache-Control "public, no-transform";

        # Whitelists production domains and your dedicated React VM
        valid_referers none blocked yourwebapp.com *.yourwebapp.com localhost localhost:3000 192.168.0.200;

        if ($invalid_referer) {
            return 403;
        }
    }

    location /hello {
        default_type text/plain;
        return 200 "Hello Again!, $arg_name!";
    }

}
