events { 
    worker_connections 1024; 
}


http {

     # Define the custom reverse proxy logging format
    log_format proxy_logging '[$time_local] Client: $remote_addr '
                     'RealIP: $http_x_real_ip '
                     'Request: "$request" Status: $status '
                     'Upstream: $upstream_addr '
                     'Upstream_Status: $upstream_status '
                     'Request_Time: $request_time '
                     'Upstream_Response_Time: $upstream_response_time';

    # OPTION A: Route all access logs to standard output (stdout) using the custom format
    access_log /dev/stdout proxy_logging;
        
    # Define the backend address for your separate core API container
    upstream core_api {
        server 192.168.0.201:5000;
    }

     # Define the backend address for your React container
    upstream react_frontend {
        server 192.168.0.200:3000;
    }

    upstream image_server {
        server 192.168.0.200:3500;
    }

    server {
        listen 80;
        
        # Replace this with vm0's actual IP address or local domain name
        server_name 192.168.0.200; 

         # Routes standard traffic to your React frontend container
        location / {
            proxy_pass http://react_frontend;
            
            # Pass essential headers so the React app understands network context
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Routes standard traffic to image server
        location /uploads/ {
            proxy_pass http://image_server;
            
            # Pass essential headers so the React app understands network context
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        # Routes standard API requests (like /api/Photos/...) directly to your API container
        location /api/ {
            proxy_pass http://core_api;
            
            # Pass essential headers so the .NET runtime understands network context
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Catch-all block for errors or missing routes
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
}

