server_inventory:
  app_proxy_server:
    vm_id: 200
    cores: 2
    ram: 2048
    ip_address: "10.10.10.110/24"
    gateway: "10.10.10.1"
    ssh_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGIKOXhR4eQgQgUqcRkY1g6xyjQbnM7++K/5PgOluZPj developer@DESKTOP-IUTPP9P My key"
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBL8soF08x0Xr4vCgQ/heYO8HHbVYz33ndBACW0vVO69 sim.checkland@outlook.com runner to vm"
    username: "svc"

  api_server:
    vm_id: 201
    cores: 2
    ram: 2048
    ip_address: "10.10.10.201/24"
    gateway: "10.10.10.1"
    ssh_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGIKOXhR4eQgQgUqcRkY1g6xyjQbnM7++K/5PgOluZPj developer@DESKTOP-IUTPP9P My key"
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBL8soF08x0Xr4vCgQ/heYO8HHbVYz33ndBACW0vVO69 sim.checkland@outlook.com runner to vm"
    username: "svc"
