---
- name: "🌐 Baseline OS Hardening "
  hosts: all # 🟢 Targets every machine inside inventory.ini
  become: true

  tasks:
    - name: Install baseline system prerequisites
      apt:
        name:
          [
            apt-transport-https,
            ca-certificates,
            curl,
            gnupg,
            software-properties-common,
          ]
        state: present
        update_cache: yes
      become: true
      register: apt_result
      until: apt_result is success
      retries: 15
      delay: 10

    - name: Assign deployment user to the docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
