---
- name: Apply base system configurations to all VMs
  hosts: all
  become: true
  vars_files:
    - "../server-set-20-infra.yml" # Imports the exact same config list

  tasks:
    - name: Print a message showing target properties
      ansible.builtin.debug:
        msg: "Configuring {{ inventory_hostname }} with RAM allotment from global config"
