---
- name: "🔒 Proxy Server Specific Configuration"
  hosts: app-proxy-server # 🎯 ONLY targets your proxy VM node
  become: true

  tasks:
    - name: Create Nginx infrastructure directories
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: directory
        owner: root
        group: root
        mode: "{{ item.mode }}"
      loop:
        - { path: "/etc/nginx/ssl", mode: "0700" }
        - { path: "/opt/nginx-proxy/", mode: "0755" }
