name: Deploy Nginx Reverse Proxy to vm0

on:
  push:
    branches:
      - main
    paths:
     - "proxy/**"
     - ".github/workflows/deploy-proxy.yml"

jobs:
  deploy:
    # Tells GitHub to execute this job on your local Linux runner
    runs-on: [self-hosted, linux]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy Proxy Config Files to vm0
        run: |
          # 1. Create /opt/nginx-proxy/ (Standard Linux convention)
          ssh -i /home/github-runner/.ssh/runner-to-vm1 -o StrictHostKeyChecking=no "${{ secrets.VM0_USER }}@${{ secrets.VM0_HOST }}" "mkdir -p /opt/nginx-proxy/"

          # 2. Copy files into /opt/nginx-proxy/
          scp -i /home/github-runner/.ssh/runner-to-vm1 -o StrictHostKeyChecking=no proxy/* ${{ secrets.VM0_USER }}@${{ secrets.VM0_HOST }}:/opt/nginx-proxy/


      - name: Start Nginx Proxy Container on vm0 -
        run: |
          # Remotely triggers the container restart on vm0
          ssh ${{ secrets.VM0_USER }}@${{ secrets.VM0_HOST }} "cd /opt/nginx-proxy && docker compose down && docker compose up -d --force-recreate"
