name: Deploy Image Server Changes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, linux] 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v5

    - name: SSH to Proxmox and Apply Changes
    
      env:
        SSH_USER: ${{ secrets.VM_USER }}
        KEY_PATH: C:\Users\Developer\.ssh\id_ed25519
      run: |
        # Standard, native Linux SSH execution. Simple, clear, and bulletproof.
         ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no "${SSH_USER}@192.168.0.202" 
           "cd ~/react-photo-app && git pull origin main && docker-compose up -d && docker exec photo-nginx nginx -s reload"
