name: Deploy API Server Changes

on:
  push:
    branches:
      - main
    paths:
      - "api-server/**"
      - ".github/workflows/vm1-deploy-api.yml"

jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5 

      - name: Copy API Deployment and Code to Proxmox
        run: |
          ssh -i /root/.ssh/runner-vm -o StrictHostKeyChecking=no "${{ secrets.VM2_USER }}@192.168.0.201" "rm -rf ~/react-photo-app/api-server"
          
          # Added quotes around the destination to fix the YAML parser error
          scp -i /root/.ssh/runner-vm -o StrictHostKeyChecking=no -r api-server/ "${{ secrets.VM2_USER }}@192.168.0.201:~/react-photo-app/api-server"

      - name: Copy Nginx to Proxmox
        run: |
          ssh -i /root/.ssh/runner-vm -o StrictHostKeyChecking=no "${{ secrets.VM2_USER }}@192.168.0.201" "rm -rf ~/react-photo-app/nginx.conf"
          
          # Added quotes around the destination and removed incorrect -r for a single file
          scp -i /root/.ssh/runner-vm -o StrictHostKeyChecking=no api-server/nginx.conf "${{ secrets.VM2_USER }}@192.168.0.201:~/react-photo-app/nginx.conf"

      - name: Remote Restart via SSH
        env:
          API_SECRET: ${{ secrets.MONGODB_KEY }}
        run: |
          ssh -i /root/.ssh/runner-vm -o StrictHostKeyChecking=no "${{ secrets.VM2_USER }}@192.168.0.201" "echo \"MONGODB_KEY=$API_SECRET\" > ~/react-photo-app/api-server/.env"
          ssh -i /root/.ssh/runner-vm -o StrictHostKeyChecking=no "${{ secrets.VM2_USER }}@192.168.0.201" "cd ~/react-photo-app/api-server && docker compose down && docker compose up -d --build"
