name: Deploy Nginx Reverse Proxy to vm20

on:
  workflow_call:

jobs:
  deploy:
    # Tells GitHub to execute this job on your local Linux runner
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Clear old SSH host key
        run: |
          # Remove the old key for your target IP or Domain
          ssh-keygen -f "/root/.ssh/known_hosts" -R "${{ secrets.VM20_HOST }}" || true

          # Force add the new key so SSH trusts the server again
          ssh-keyscan -H "${{ secrets.VM20_HOST }}" >> /root/.ssh/known_hosts

      - name: Copy Proxy Config Files to vm20
        run: |
          # 1. Copy files into /opt/nginx-proxy/
          scp -i /root/.ssh/runner-vm -o StrictHostKeyChecking=no proxy/* ${{ secrets.VM20_USER }}@${{ secrets.VM20_HOST }}:/opt/nginx-proxy/

      - name: Start Nginx Proxy Container on vm0 -
        run: |

          ssh -i /root/.ssh/runner-vm -o StrictHostKeyChecking=no "${{ secrets.VM20_USER }}@${{ secrets.VM20_HOST }}" "
            cd /opt/nginx-proxy && 
            docker compose down && 
            docker compose up -d --force-recreate
          "
